name: example

options:
  deploymentTarget:
    iOS: "11.0"
  usesTabs: false
  tabWidth: 2
  indentWidth: 2
  defaultConfig: Release

fileGroups:
  - main.jsbundle

settings:
  base:
    DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
    CODE_SIGN_STYLE: Automatic
    LD_RUNPATH_SEARCH_PATHS:
      - /usr/lib/swift
      - $(inherited)
    LIBRARY_SEARCH_PATHS:
      - $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
      - $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
      - $(inherited)
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
    CLANG_CXX_LANGUAGE_STANDARD: gnu++0x
    GCC_C_LANGUAGE_STANDARD: gnu99

  configs:
    Debug:
      COPY_PHASE_STRIP: false
      MTL_ENABLE_DEBUG_INFO: true
      GCC_SYMBOLS_PRIVATE_EXTERN: false
    Release:
      COPY_PHASE_STRIP: true
      MTL_ENABLE_DEBUG_INFO: false

targets:
  example:
    type: application
    platform: iOS
    sources:
      - example
    scheme:
      parallelizeBuild: false
    settings:
      base:
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1
        PRODUCT_BUNDLE_IDENTIFIER: com.example.react-native-baidu-mtj
        SWIFT_OBJC_BRIDGING_HEADER: example/example-Bridging-Header.h
        CLANG_ENABLE_MODULES: true
        OTHER_LDFLAGS:
          - $(inherited)
          - -ObjC
          - -lc++
      configs:
        Debug:
          ENABLE_BITCODE: false
          GCC_PREPROCESSOR_DEFINITIONS:
            - $(inherited)
    preBuildScripts:
      - name: Start Packager
        script: |
          export RCT_METRO_PORT="${RCT_METRO_PORT:=8081}"
          echo "export RCT_METRO_PORT=${RCT_METRO_PORT}" > "${SRCROOT}/../node_modules/react-native/scripts/.packager.env"
          if [ -z "${RCT_NO_LAUNCH_PACKAGER+xxx}" ] ; then
            if nc -w 5 -z localhost ${RCT_METRO_PORT} ; then
              if ! curl -s "http://localhost:${RCT_METRO_PORT}/status" | grep -q "packager-status:running" ; then
                echo "Port ${RCT_METRO_PORT} already in use, packager is either not running or not running correctly"
                exit 2
              fi
            else
              open "$SRCROOT/../node_modules/react-native/scripts/launchPackager.command" || echo "Can't start packager automatically"
            fi
          fi
        showEnvVars: false
    postBuildScripts:
      - name: Bundle React Native code and images
        script: |
          set -e

          export NODE_BINARY=node
          ../node_modules/react-native/scripts/react-native-xcode.sh
